#!/bin/bash

error() {
  echo "Error: $1" >&2
  exit 1
}

usage() {
  local usage_string
  usage_string="Usage: git_sync OPTIONS
  OPTIONS
  -h                    Display this help message"
  echo "${usage_string}"
}

main() {
  if (( $# == 0 )); then
      usage
      error "git_sync requires at least one option"
  fi
  while getopts :h opt; do
    case "${opt}" in
      h) usage; exit 0 ;;
      *) error "Unkown option: ${opt}" ;;
    esac
  done
}

main "$@"
